name: Bandit Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run bandit
        uses: tj-actions/bandit
        with:
          # Optional: specify targets, e.g., 'app' or '.'
          targets: "."
          # Optional: specify severity level, e.g., 'LOW', 'MEDIUM', 'HIGH'
          # level: MEDIUM
          # Optional: specify confidence level, e.g., 'LOW', 'MEDIUM', 'HIGH'
          # confidence: MEDIUM
          # Optional: specify output format, e.g., 'json', 'csv', 'xml', 'html'
          # format: json
          # Optional: specify output file path
          # output_file: bandit-report.json
