name: Dast

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t vulnerable-image .

      - name: Run Docker container
        run: docker run -d -p 80:80 vulnerable-image

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: vulnerable-image
          format: table
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: 1
