name: Dast

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t vulnerable-image .

      - name: Run Docker container
        run: docker run -d -p 80:80 vulnerable-image

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          # token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:80/'
          # rules_file_name: '.zap/rules.tsv'
          # cmd_options: '-a'
